# Generated by Django 4.0.2 on 2022-06-17 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Language',
        ),
        migrations.DeleteModel(
            name='Level',
        ),
        migrations.AddField(
            model_name='classweekday',
            name='class_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='main.class'),
        ),
        migrations.AlterField(
            model_name='class',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='courses.course'),
        ),
        migrations.AlterField(
            model_name='class',
            name='teacher_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.teacher'),
        ),
        migrations.AlterField(
            model_name='classstudent',
            name='class_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.class'),
        ),
        migrations.AlterField(
            model_name='classstudent',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.student'),
        ),
        migrations.AlterField(
            model_name='classweekday',
            name='weekday_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.weekday'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='class_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.class'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.paymentmethod'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.student'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='staffaccount',
            name='staff_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.staff'),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='studentaccount',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.student'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='teacheraccount',
            name='teacher_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.teacher'),
        ),
    ]
