# Generated by Django 4.0.2 on 2022-06-17 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_delete_category_delete_course_delete_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classweekday',
            name='class_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.class'),
        ),
    ]
