# Generated by Django 4.0.2 on 2022-06-18 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_ngayhoc_rename_name_category_phanloai_and_more'),
        ('main', '0004_remove_class_price_alter_teacher_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classstudent',
            name='class_id',
        ),
        migrations.RemoveField(
            model_name='classstudent',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='classweekday',
            name='class_id',
        ),
        migrations.RemoveField(
            model_name='classweekday',
            name='weekday_id',
        ),
        migrations.RemoveField(
            model_name='staffaccount',
            name='staff_id',
        ),
        migrations.AlterField(
            model_name='payment',
            name='class_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='courses.lophoc'),
        ),
        migrations.DeleteModel(
            name='Class',
        ),
        migrations.DeleteModel(
            name='ClassStudent',
        ),
        migrations.DeleteModel(
            name='ClassWeekday',
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
        migrations.DeleteModel(
            name='StaffAccount',
        ),
        migrations.DeleteModel(
            name='Weekday',
        ),
    ]
