# Generated by Django 4.0.2 on 2022-06-26 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_contact_user_userprofileinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentaccount',
            name='login',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='studentaccount',
            name='password',
            field=models.CharField(max_length=50),
        ),
    ]
