# Generated by Django 4.0.2 on 2022-06-26 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_studentaccount_login_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacheraccount',
            name='teacher_id',
        ),
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='username',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='teacher',
            name='password',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='teacher',
            name='username',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.DeleteModel(
            name='StudentAccount',
        ),
        migrations.DeleteModel(
            name='TeacherAccount',
        ),
    ]
