# Generated by Django 4.0.2 on 2022-06-28 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0027_alter_lophoc_hours1_alter_lophoc_hours2_and_more'),
        ('main', '0011_alter_student_password_alter_student_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='class_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='courses.lophoc'),
        ),
    ]
