# Generated by Django 4.0.2 on 2022-06-28 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0029_alter_lophoc_hours1_alter_lophoc_hours2'),
        ('main', '0012_student_class_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='class_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.lophoc'),
        ),
    ]
