# Generated by Django 4.0.2 on 2022-06-17 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_rename_lessons_course_ten_lop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='level_id',
        ),
        migrations.RemoveField(
            model_name='course',
            name='term',
        ),
        migrations.DeleteModel(
            name='Level',
        ),
    ]
