# Generated by Django 4.0.2 on 2022-06-17 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_course_level_id_remove_course_term_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='photo',
            field=models.ImageField(default='courses/images/course-1.jpg', upload_to='courses/images'),
        ),
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.FloatField(default=500000),
        ),
    ]
