# Generated by Django 4.0.2 on 2022-06-18 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_ngayhoc_rename_name_category_phanloai_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='ten_khoahoc',
            field=models.CharField(max_length=150),
        ),
    ]
