# Generated by Django 4.0.2 on 2022-06-18 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_course_ten_khoahoc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='price',
        ),
        migrations.AddField(
            model_name='lophoc',
            name='price',
            field=models.FloatField(default=500000),
        ),
    ]
