# Generated by Django 4.0.2 on 2022-06-18 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_remove_course_price_lophoc_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lst_Ngay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='ngayhoc',
            name='ngay',
        ),
        migrations.AddField(
            model_name='ngayhoc',
            name='days',
            field=models.ManyToManyField(to='courses.Lst_Ngay'),
        ),
    ]
