# Generated by Django 4.0.2 on 2022-06-18 08:03

import courses.myfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_lst_ngay_remove_ngayhoc_ngay_ngayhoc_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ngayhoc',
            name='days',
        ),
        migrations.AddField(
            model_name='ngayhoc',
            name='days',
            field=courses.myfields.FieldNgayTrongTuan(choices=[('Chủ Nhật', 'Chủ Nhật'), ('Thứ Ba', 'Thứ Ba'), ('Thứ Bảy', 'Thứ Bảy'), ('Thứ Hai', 'Thứ Hai'), ('Thứ Năm', 'Thứ Năm'), ('Thứ Sáu', 'Thứ Sáu'), ('Thứ Tư', 'Thứ Tư')], default='Chủ Nhật', max_length=8),
        ),
        migrations.DeleteModel(
            name='Lst_Ngay',
        ),
    ]
