# Generated by Django 4.0.2 on 2022-06-18 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_selectweekday_remove_ngayhoc_days_ngayhoc_days'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SelectWeekday',
            new_name='Weekday',
        ),
    ]
