# Generated by Django 4.0.2 on 2022-06-18 09:26

import courses.myfields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_rename_selectweekday_weekday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='giohoc',
            name='class_id',
        ),
        migrations.AddField(
            model_name='ngayhoc',
            name='class_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='courses.lophoc'),
        ),
        migrations.RemoveField(
            model_name='ngayhoc',
            name='days',
        ),
        migrations.AddField(
            model_name='ngayhoc',
            name='days',
            field=courses.myfields.FieldNgayTrongTuan(choices=[('Thứ Hai', 'Thứ Hai'), ('Thứ Ba', 'Thứ Ba'), ('Thứ Tư', 'Thứ Tư'), ('Thứ Năm', 'Thứ Năm'), ('Thứ Sáu', 'Thứ Sáu'), ('Thứ Bảy', 'Thứ Bảy'), ('Chủ Nhật', 'Chủ Nhật')], default='Chủ Nhật', max_length=8),
        ),
        migrations.DeleteModel(
            name='Weekday',
        ),
    ]
