# Generated by Django 4.0.2 on 2022-06-18 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_remove_giohoc_class_id_ngayhoc_class_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ngayhoc',
            name='class_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='courses.lophoc'),
        ),
    ]
