# Generated by Django 4.0.2 on 2022-06-18 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_alter_ngayhoc_class_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lophoc',
            name='price',
        ),
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.FloatField(default=500000),
        ),
        migrations.AlterField(
            model_name='giohoc',
            name='hours',
            field=models.TimeField(),
        ),
    ]
