# Generated by Django 4.0.2 on 2022-06-18 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_remove_lophoc_price_course_price_alter_giohoc_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='lophoc',
            name='description',
            field=models.CharField(default='', max_length=500),
        ),
    ]
