# Generated by Django 4.0.2 on 2022-06-18 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_lophoc_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lophoc',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
