# Generated by Django 4.0.2 on 2022-06-21 13:01

import ckeditor_uploader.fields
import courses.myfields
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_student_date_birth_alter_student_email'),
        ('courses', '0017_alter_course_description_alter_lophoc_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaiHoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_bai', models.CharField(max_length=50)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='ngayhoc',
            name='class_id',
        ),
        migrations.RemoveField(
            model_name='lophoc',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='lophoc',
            name='start_date',
        ),
        migrations.AddField(
            model_name='classstudent',
            name='discount',
            field=models.FloatField(default=100),
        ),
        migrations.AddField(
            model_name='course',
            name='course_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='course_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lophoc',
            name='days',
            field=courses.myfields.FieldNgayTrongTuan(choices=[('Thứ Hai', 'Thứ Hai'), ('Thứ Ba', 'Thứ Ba'), ('Thứ Tư', 'Thứ Tư'), ('Thứ Năm', 'Thứ Năm'), ('Thứ Sáu', 'Thứ Sáu'), ('Thứ Bảy', 'Thứ Bảy'), ('Chủ Nhật', 'Chủ Nhật')], default='Chủ Nhật', max_length=8),
        ),
        migrations.AddField(
            model_name='lophoc',
            name='hours',
            field=models.TimeField(default=datetime.datetime(2022, 6, 21, 20, 1, 22, 40547)),
        ),
        migrations.AddField(
            model_name='lophoc',
            name='lophoc_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lophoc',
            name='lophoc_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lophoc',
            name='price',
            field=models.FloatField(default=500000),
        ),
        migrations.AlterField(
            model_name='lophoc',
            name='teacher_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='main.teacher'),
        ),
        migrations.DeleteModel(
            name='GioHoc',
        ),
        migrations.DeleteModel(
            name='NgayHoc',
        ),
        migrations.AddField(
            model_name='baihoc',
            name='lophoc_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='courses.lophoc'),
        ),
    ]
