# Generated by Django 4.0.2 on 2022-06-22 00:54

import courses.myfields
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_student_date_birth_alter_student_email'),
        ('courses', '0018_baihoc_remove_ngayhoc_class_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='price',
            new_name='course_price1',
        ),
        migrations.RemoveField(
            model_name='lophoc',
            name='days',
        ),
        migrations.RemoveField(
            model_name='lophoc',
            name='hours',
        ),
        migrations.AddField(
            model_name='course',
            name='course_price2',
            field=models.FloatField(default=500000),
        ),
        migrations.AddField(
            model_name='lophoc',
            name='days1',
            field=courses.myfields.FieldNgayTrongTuan(blank=True, choices=[('Thứ Hai', 'Thứ Hai'), ('Thứ Ba', 'Thứ Ba'), ('Thứ Tư', 'Thứ Tư'), ('Thứ Năm', 'Thứ Năm'), ('Thứ Sáu', 'Thứ Sáu'), ('Thứ Bảy', 'Thứ Bảy'), ('Chủ Nhật', 'Chủ Nhật')], default='Chủ Nhật', max_length=8),
        ),
        migrations.AddField(
            model_name='lophoc',
            name='days2',
            field=courses.myfields.FieldNgayTrongTuan(blank=True, choices=[('Thứ Hai', 'Thứ Hai'), ('Thứ Ba', 'Thứ Ba'), ('Thứ Tư', 'Thứ Tư'), ('Thứ Năm', 'Thứ Năm'), ('Thứ Sáu', 'Thứ Sáu'), ('Thứ Bảy', 'Thứ Bảy'), ('Chủ Nhật', 'Chủ Nhật')], default='Chủ Nhật', max_length=8),
        ),
        migrations.AddField(
            model_name='lophoc',
            name='days3',
            field=courses.myfields.FieldNgayTrongTuan(blank=True, choices=[('Thứ Hai', 'Thứ Hai'), ('Thứ Ba', 'Thứ Ba'), ('Thứ Tư', 'Thứ Tư'), ('Thứ Năm', 'Thứ Năm'), ('Thứ Sáu', 'Thứ Sáu'), ('Thứ Bảy', 'Thứ Bảy'), ('Chủ Nhật', 'Chủ Nhật')], default='Chủ Nhật', max_length=8),
        ),
        migrations.AddField(
            model_name='lophoc',
            name='hours1',
            field=models.TimeField(default=datetime.datetime(2022, 6, 22, 7, 53, 52, 394929)),
        ),
        migrations.AddField(
            model_name='lophoc',
            name='hours2',
            field=models.TimeField(default=datetime.datetime(2022, 6, 22, 7, 53, 52, 394929)),
        ),
        migrations.AlterField(
            model_name='lophoc',
            name='teacher_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.teacher'),
        ),
    ]
