# Generated by Django 4.0.2 on 2022-06-28 15:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0027_alter_lophoc_hours1_alter_lophoc_hours2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lophoc',
            name='hours1',
            field=models.TimeField(default=datetime.datetime(2022, 6, 28, 22, 46, 26, 903444)),
        ),
        migrations.AlterField(
            model_name='lophoc',
            name='hours2',
            field=models.TimeField(default=datetime.datetime(2022, 6, 28, 22, 46, 26, 903444)),
        ),
    ]
