# Generated by Django 4.0.2 on 2022-06-30 12:40

import ckeditor_uploader.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0029_alter_lophoc_hours1_alter_lophoc_hours2'),
    ]

    operations = [
        migrations.AddField(
            model_name='baihoc',
            name='lecture',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
        migrations.AlterField(
            model_name='lophoc',
            name='hours1',
            field=models.TimeField(default=datetime.datetime(2022, 6, 30, 19, 40, 50, 970866)),
        ),
        migrations.AlterField(
            model_name='lophoc',
            name='hours2',
            field=models.TimeField(default=datetime.datetime(2022, 6, 30, 19, 40, 50, 970866)),
        ),
    ]
