# Generated by Django 4.0.2 on 2022-07-01 05:35

import datetime
from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0030_baihoc_lecture_alter_lophoc_hours1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baihoc',
            name='lecture',
            field=embed_video.fields.EmbedVideoField(blank=True),
        ),
        migrations.AlterField(
            model_name='lophoc',
            name='hours1',
            field=models.TimeField(default=datetime.datetime(2022, 7, 1, 12, 35, 20, 78068)),
        ),
        migrations.AlterField(
            model_name='lophoc',
            name='hours2',
            field=models.TimeField(default=datetime.datetime(2022, 7, 1, 12, 35, 20, 78068)),
        ),
    ]
