# Generated by Django 4.0.2 on 2022-07-07 10:53

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0034_alter_lophoc_hours1_alter_lophoc_hours2'),
    ]

    operations = [
        migrations.AddField(
            model_name='lophoc',
            name='discount',
            field=models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='lophoc',
            name='hours1',
            field=models.TimeField(default=datetime.datetime(2022, 7, 7, 17, 53, 15, 805146)),
        ),
        migrations.AlterField(
            model_name='lophoc',
            name='hours2',
            field=models.TimeField(default=datetime.datetime(2022, 7, 7, 17, 53, 15, 805146)),
        ),
    ]
