# Generated by Django 4.0.2 on 2022-07-07 14:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0036_alter_lophoc_discount_alter_lophoc_hours1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lophoc',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='lophoc',
            name='hours1',
            field=models.TimeField(default=datetime.datetime(2022, 7, 7, 21, 37, 25, 505966)),
        ),
        migrations.AlterField(
            model_name='lophoc',
            name='hours2',
            field=models.TimeField(default=datetime.datetime(2022, 7, 7, 21, 37, 25, 505966)),
        ),
    ]
