# Generated by Django 4.0.6 on 2022-07-13 02:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0037_alter_lophoc_discount_alter_lophoc_hours1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lophoc',
            name='hinh',
            field=models.ImageField(default='courses/images/course-1.jpg', upload_to='courses/images'),
        ),
        migrations.AlterField(
            model_name='lophoc',
            name='discount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='lophoc',
            name='hours1',
            field=models.TimeField(default=datetime.datetime(2022, 7, 13, 9, 48, 9, 573012)),
        ),
        migrations.AlterField(
            model_name='lophoc',
            name='hours2',
            field=models.TimeField(default=datetime.datetime(2022, 7, 13, 9, 48, 9, 573012)),
        ),
    ]
